### ISSUE TITLE
problems in sensor_height correct and reflectance filter

### ISSUE THREAD

**Issue by XingyanCao** [armstonj/pylidar-tls-canopy#1]
Dear John,

Thanks for sharing the private repository with me and it's very useful to generate PAI and PAVD, while I found some problems in sensor height correction and reflectance filtering.

For the sensor height correction, in the **line 127 of plant_profile.py**, the script may be **self.transform** rather than **f.transform** if the transformation matrix were added in the **_init​_**  funtion. . I add some codes to let the function read the transform file, but no value returns after changing the script. 

In the notebook, you recommended doing reflectance filter, and this caused _boolean index did not match_ indexed array along dimension 0.

**Data info of the input:**
Only Rxp file acquired using Riegl VZ-400 and the corresponding DAT file were input.

**Comment by armstonj** [comment]
I've committed a fix for this issue:
https://github.com/armstonj/pylidar-tls-canopy/commit/19e9a2a3106adccbf88d2288a9ca27bbb6565567

Please test and let me know if you encounter further issues.

**Comment by armstonj** [comment]
@XingyanCao is this still an issue?

**Comment by XingyanCao** [comment]
Hello John, 

Thanks for your help, I update the package through reinstalling all of things following your directions. But it does not work, a new problem occurred. The terminal and notebook both report error being not related to the script.

I firstly tried in notebook, and the notebook reported that "The kernel for xX.ipynb appears to have died when fitting the ground plane , it will restart automatically". Then I tried in the terminal with commands, after showing "Fitting the ground plane", showing "killed".

Kind regards,
Xingyan

**Comment by armstonj** [comment]
Hi Xingyan, I'm closing this issue because the latest problem you reported are likely not related to the original issue. If you still experience any problems with the latest version (0.4) please submit a new issue.
